name: mytodo
description: "Offline task management and journal app"
publish_to: 'none'
version: 1.1.1+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.5.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  record: ^6.2.0
  audioplayers: ^6.1.0
  table_calendar: ^3.1.2
  home_widget: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo_light.png
    - assets/splash_logo_dark.png
